version: '3.7'
services:
 db-postgres:
   image: "postgres:12"
   restart: always
   expose:
     - 5432
   environment:
     - POSTGRES_USER=db_user
     - POSTGRES_PASSWORD=db_password
     - POSTGRES_DB=jogging_times
 api:
   build: .
   restart: always
   ports:
    - "5000:5000"
   environment:
     - APP_SETTINGS=server.config.StagingConfig
   depends_on:
     - db-postgres
